trigger:
- master

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get -y install rng-tools
    openssl dhparam -out dh512.pem 512
    openssl dhparam -out dh2048.pem 2048
    chmod 644 dh512.pem dh2048.pem
    openssl req -nodes -newkey rsa:2048 -x509 -keyout key.pem -out cert.pem -days 3650 -subj '/CN=localhost'
    docker-compose -p smtp build
    docker-compose -p smtp up -d
    sleep 10s
    docker-compose -p smtp down
    docker volume rm smtp_postfix

  displayName: 'docker-compose build'
