#!/bin/bash
set -e

command_directory=$(postconf -h command_directory)
config_directory=$(postconf -h config_directory)

mkdir -p /etc/ssl/server

postconf -e "inet_interfaces=all" \
            "inet_protocols=ipv4" \
            "mynetworks=${MY_NETWORKS}" \
            "relayhost=${SMTP_SERVER}" \
            "smtp_sasl_auth_enable=yes" \
            "smtp_sasl_password_maps=lmdb:$config_directory/sasl_passwd" \
            "smtp_sasl_mechanism_filter=AUTH LOGIN" \
            "smtp_sasl_security_options=" \
            "smtputf8_enable=no" \
            "smtp_destination_rate_delay=1" \
            "relay_domains=" \
            "message_size_limit=104857600" \
            "mailbox_size_limit=104857600" \
            "maillog_file = /dev/stdout" \
            "smtpd_tls_loglevel=1" \
            "smtp_tls_loglevel=1" \
            "smtpd_tls_received_header=yes" \
            "smtpd_tls_ciphers=high" \
            "smtpd_tls_protocols=!SSLv2,!SSLv3" \
            "smtpd_use_tls=yes" \
            "smtp_use_tls=yes" \
            "smtpd_tls_session_cache_database=lmdb:\${data_directory}/smtpd_scache" \
            "smtp_tls_session_cache_database=lmdb:\${data_directory}/smtp_scache" \
            "smtpd_tls_cert_file=/etc/ssl/server/cert.pem" \
            "smtpd_tls_key_file=/etc/ssl/server/key.pem" \
            "smtp_tls_CApath=/etc/ssl/certs" \
            "smtpd_tls_CApath=/etc/ssl/certs" \
            "always_add_missing_headers = yes" \
            "smtpd_tls_dh1024_param_file=\${config_directory}/dh2048.pem" \
            "smtpd_tls_dh512_param_file=\${config_directory}/dh512.pem" \
            "mime_header_checks=regexp:$config_directory/header_checks" \
            "header_checks=regexp:$config_directory/header_checks" \
            "smtpd_forbidden_commands=CONNECT,GET,POST,USER,PASS"

echo "${SMTP_SERVER}    ${SMTP_USERNAME}:${SMTP_PASSWORD}" | postmap -i "lmdb:/$config_directory/sasl_passwd"

if [[ -n "$ROOT_ALIAS" ]]; then
    if [[ -f /etc/postfix/aliases ]]; then
        sed -i '/^root:/d' /etc/postfix/aliases
    fi
    echo "root: $ROOT_ALIAS" >> /etc/postfix/aliases
    /usr/bin/newaliases
fi

cp /staging/dh*.pem "$config_directory/" && chown root "$config_directory/"dh*.pem \
    && chmod 644 "$config_directory/"dh*.pem
mv /staging/header_checks "$config_directory/header_checks" \
    && chmod 644 "$config_directory/header_checks"
postmap "$config_directory/header_checks"

"$command_directory"/postfix check 2>&1

exec "$command_directory"/postfix start-fg
